---
title: "BIMM 143 Class 19 Population Analysis (Extra Credit)"
author: "Mi Tran A15556214"
date: "12/5/2021"
output: pdf_document
---
> Q13. Read this file into R and determine the sample size for each genotype and their
corresponding median expression levels for each of these genotypes.

```{r}
M <- read.table("https://bioboot.github.io/bggn213_f17/class-material/rs8067378_ENSG00000172057.6.txt")
head(M)
```

```{r}
table(M$geno)
```

```{r}
library(dplyr)
```
```{r}
AA <- filter(M, geno == "A/A")
head(AA)
```
```{r}
mean(AA$exp)
```

```{r}
AG <- filter(M, geno == "A/G")
head(AG)
```

```{r}
mean(AG$exp)
```

```{r}
GG <- filter(M, geno == "G/G")
head(GG)
```
```{r}
mean(GG$exp)
```

> Q14. Generate a boxplot with a box per genotype, what could you infer from the relative
expression value between A/A and G/G displayed in this plot? Does the SNP effect the
expression of ORMDL3?

```{r}
library(ggplot2)
```
```{r}
ggplot(M) + 
  aes(geno, exp, col = geno) + 
  geom_boxplot()
```








